### ISSUE TITLE
Download box canvas widens each time a book is clicked

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/get-books-activity#24]
The VBox at the bottom of the activity - where you can download a book - increases in size each time a book is clicked.

**Comment by quozl** [comment]
The whole window increases in width, with the stop button moving off the display.  Reproduced on Ubuntu 18.04 with v18.1 df73ebaac37b7b2bf621d44342f7e10d34fe5317 by clicking on the Feedbooks "most popular" catalog, then on a series of titles.
