### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/get-books-activity#33]
https://github.com/sugarlabs/get-books-activity/pulls help wanted.

**Comment by Saumya-Mishra9129** [comment]
Hey! I would like to work on this issue.

**Comment by quozl** [comment]
Thanks.  You're welcome to, as is anybody else.  See [latest pull request comments](https://github.com/sugarlabs/get-books-activity/pull/31) for the progress so far and some of the next steps.

**Comment by quozl** [comment]
Is done for v20
